import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import { Navigation } from '@/components/navigation'
import Link from 'next/link'
import { client, urlFor } from '@/lib/sanity'
import { SanityDocument } from 'next-sanity'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Blog',
  description: 'Generated by create next app',
}

async function getData() {
  const query = "*[_type == 'categories']"
  const data = await client.fetch(query)
  return data
}

// const links = [
//   { title: 'Productivity', href: '/blog/categories/productivity' },
//   { title: 'Templates', href: '/blog/categories/templates' },
//   { title: 'Wallpapers', href: '/blog/categories/wallpapers' },
// ]

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const cats = await getData()

  return (
    <>
      {/* <div className='flex space-x-4 justify-center pt-20 lg:pt-[8rem]'>
        <Link
          href={`/blog`}
          className='first-letter:uppercase'
        >
          All
        </Link>
        {cats.map((cat: SanityDocument, i: number) => (
          <Link
            key={i}
            href={`/blog/categories/${cat.slug.current}`}
            className='first-letter:uppercase'
          >
            {cat.title}
          </Link>
        ))}
      </div> */}
      {children}
    </>
  )
}
