import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import { Navigation } from '@/components/navigation'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Blog',
  description: 'Generated by create next app',
}
const links = [
  { title: 'Productivity', href: '/blog/categories/productivity' },
  { title: 'Templates', href: '/blog/categories/templates' },
  { title: 'Wallpapers', href: '/blog/categories/wallpapers' },
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <div className='flex space-x-4 justify-center pt-20 lg:pt-[12rem]'>
        {links.map((link, i) => (
          <Link
            key={i}
            href={link.href}
          >
            {link.title}
          </Link>
        ))}
      </div>
      {children}
    </>
  )
}
